gaits:
  home: {home_sit: MIV, home_stand: MIV}
  set_ankle_to_five: {set_ankle_to_five: angle_to_five_degrees}
  set_ankle_to_zero: {set_ankle_to_zero: angle_to_zero_degrees}
  side_close_reveal: {left_close: sjaan_left}
  side_open_reveal: {left_open: sjaan_left}
  side_step_left: {left_open: MIV_optimized, right_close: MIV}
  side_step_right: {left_close: MIV, right_open: MIV_optimized}
  single_step_normal: {left_close: MIV, right_open: MIV}
  single_step_small: {left_close: MIV_less_hip_flexion, right_open: MIV_less_hip_flexion}
  sit: {sit_down: MIV_fluent, sit_home: MIV}
  sofa_sit: {sit_down: MIV_changed_velocities, sit_home: MIV}
  sofa_stand: {prepare_stand_up: MIV, stand_up: MIV_changed_velocities}
  stand: {prepare_stand_up: MIV, stand_up: MIV_fluent}
  walk: {left_close: MIV_more_dorsiflexion, left_swing: 'MIV_more_dorsiflexion_1,3sec',
    right_close: MIV_more_dorsiflexion, right_open: MIV_more_dorsiflexion, right_swing: 'MIV_more_dorsiflexion_1,3sec'}
