gaits:
  home: {home_sit: home_sit_3sec, home_stand: home_stand_3sec}
  single_step: {left_close: MIV, right_open: MIV}
  sit: {sit_down: MIII, sit_home: MIII}
  stand: {prepare_stand_up: MIII, stand_up: MIII}
  walk: {left_close: MIV_2sec, left_swing: MIV, right_close: MIV, right_open: MIV,
    right_swing: MIV}
