controller_list:
  - name: fake_chain_lr_controller
    type: $(arg execution_type)
    joints:
      - left_ankle
      - left_knee
      - left_hip_fe
      - left_hip_aa
      - right_hip_aa
      - right_hip_fe
      - right_knee
      - right_ankle
  - name: fake_end_effector_controller
    type: $(arg execution_type)
    joints:
      - right_ankle
initial:  # Define initial robot poses.
#  - group: chain_lr
#    pose: home

  []