dist: xenial
sudo: required
language: python
env:
  global:
    - ROS_DISTRO=kinetic
    - ROS_PARALLEL_JOBS="-j8 -l6"
    - ROSINSTALL_FILE="$TRAVIS_BUILD_DIR/dependencies.rosinstall"
    - COLCON_OPTS="--event-handler summary+ desktop_notification- status-"
    - WORKSPACE_DIR="$HOME/ws"

before_install:
  - sudo sh -c "echo \"deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main\"
      > /etc/apt/sources.list.d/ros-latest.list"
  - sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key $ROS_KEY
  - sudo apt-get update
  - sudo apt-get install -y python-wstool python-catkin-lint ros-$ROS_DISTRO-ros-base
  - pip install colcon-common-extensions

install:
  - sudo rosdep init
  - rosdep update
  - source /opt/ros/$ROS_DISTRO/setup.bash
  - mkdir -p $WORKSPACE_DIR/src
  - cp -R $TRAVIS_BUILD_DIR $WORKSPACE_DIR/src/
  - cd $HOME/ws
  - wstool init src $ROSINSTALL_FILE
  - wstool update -t src
  - rosdep install -y --from-paths $TRAVIS_BUILD_DIR --ignore-src --rosdistro $ROS_DISTRO

script:
  - colcon build $COLCON_OPTS
  - source $WORKSPACE_DIR/install/setup.bash
  - catkin_lint -W2 $TRAVIS_BUILD_DIR
  - colcon test $COLCON_OPTS
  - colcon test-result --test-result-base $WORKSPACE_DIR/test_results --all
