dist: xenial
sudo: required
language:
- cpp
cache:
- apt
notifications:
  slack:
    secure: DiI/mSwPdfkwTxu3/JsCvIOFUW/PyEzJdmr19UA6afC7whLJuykj2Xz+dXCsABTk9DMwmI220epVPkKXmDJSgPGLvuMjvXYlWLXSYb3pqy7km6XXkEH3RxlS5FW/4ou2QlVEzFBHFg8Yr9KjT73KsXsbOSa3PQHtYBjMF5qflAjV83d6ZkRRQtkwfjdT6mtfw65XlpsZCcWa0xBvIL6FB7zUHL/SHCC2SSFV8YQwbW0hI6fzACP9S6Tt0kOq/pdnR6h/Tl9QVJXGHbLqcCQpCOKg14/QcJvhgDv9AHttn2y9qykd5L34jJuqJE+hNp1YTGY/vWV0WiC+Jtc5bDbqtgWXD96c8lH0oGMQ+7verrToljyLu98M7UlkhNCFWbJIrnL5HYsN27KfXzpO90t6m9JNPPf3qYurSswZn0Q4q8Zv0D8nCkyi7Rh6RlaiqGC4FddNdl2Ipaf7DqfKkYFiKy/MwzqFuQjGrFi+8TjmHErb8+zCwjVp8mAylpX+ZMJaoSEVk6CHtXLzdu5sO7E6/Gpbkq10Iv5KgHfllsMzdoY550a8KGr+Jm3EOZt9KE2vYMs7YA3CL5FLAi0HFQfA4L2MvbN5gfFTIGvWExTZdyiwu/cqY8Y20qBYXE3o8gvuTYkxwe4OpMNMMfH/e2hzZmGTDN7TtZbQlNriUoBOlRs=
addons:
  apt:
    packages:
    - doxygen
matrix:
  include:
  - name: Xenial kinetic
    dist: xenial
    env: ROS_DISTRO=kinetic
env:
  global:
    ROS_DISTRO: kinetic
    ROS_CI_DESKTOP: "`lsb_release -cs`"
    CI_SOURCE_PATH: "$(pwd)"
    ROSINSTALL_FILE: "$CI_SOURCE_PATH/dependencies.rosinstall"
    CATKIN_OPTIONS: "$CI_SOURCE_PATH/catkin.options"
    ROS_PARALLEL_JOBS: "-j8 -l6"
    PYTHONPATH: "$PYTHONPATH:/usr/lib/python2.7/dist-packages:/usr/local/lib/python2.7/dist-packages"
before_install:
- sudo sh -c "echo \"deb http://packages.ros.org/ros/ubuntu $ROS_CI_DESKTOP main\"
  > /etc/apt/sources.list.d/ros-latest.list"
- sudo apt-key adv --keyserver hkp://ha.pool.sks-keyservers.net:80 --recv-key 421C365BD9FF1F717815A3895523BAEEB01FA116
- sudo apt-get update -qq
- sudo apt-get install dpkg
- sudo apt-get install -y python-catkin-pkg python-rosdep python-wstool ros-$ROS_DISTRO-ros-base
- sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -sc` main"
  > /etc/apt/sources.list.d/ros-latest.list'
- wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
- source /opt/ros/$ROS_DISTRO/setup.bash
- sudo rosdep init
- rosdep update
- sudo apt-get install ros-kinetic-rosbash
- sudo apt-get install ros-kinetic-roslaunch
- pip install --user catkin_lint
- pip install --user catkin_tools_document
- sudo apt-get install python-catkin-tools
install:
- mkdir -p ~/catkin_ws/src
- cd ~/catkin_ws
- catkin init
- catkin build
- source devel/setup.bash
- cd ~/catkin_ws/src
- ln -s $CI_SOURCE_PATH .
before_script:
- cd ~/catkin_ws/src
- wstool init
- if [[ -f $ROSINSTALL_FILE ]] ; then wstool merge $ROSINSTALL_FILE ; fi
- wstool up
- cd ~/catkin_ws
- rosdep update
- rosdep install -y --from-paths src --ignore-src --rosdistro $ROS_DISTRO
- cd src
- cd ~/catkin_ws
script:
- source /opt/ros/$ROS_DISTRO/setup.bash
- cd ~/catkin_ws
- src/gait-generation/build.sh
- src/gait-generation/doc.sh
- pwd
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: "/home/travis/catkin_ws/docs/html"
  github_token: "$GH_REPO_TOKEN"
  on:
    branch: develop
