march:
  controller:
    pdb_state:
      type: march_pdb_state_controller/MarchPdbStateController
      publish_rate: 50
    joint_state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    temperature_sensor:
      type: march_temperature_sensor_controller/MarchTemperatureSensorController
      publish_rate: 1
    trajectory:
      type: model_predictive_trajectory_controller/JointTrajectoryController
      N: 20
      joints:
        - rotational_joint

      # Controller tuning parameters
      # Q and R are the weights on the states and inputs of the system respectively
      # The parameters represent the values on the diagonal of the MPC weighting matrix
      # Both parameters are required for each joint
      weights:
        rotational_joint:
          Q: [101.0, 1.0]
          R: [0.01]

      constraints:
        goal_time: 0.5
        rotational_joint:
          stopped_velocity_tolerance: 0.1
          margin_soft_limit_error: 0.5
          goal: 0.5
          trajectory: 0.6

      state_publish_rate:  25            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default
