version: "3.9"

x-gui:
  &gui-standard
  tty: true # Enables terminal in & out
  stdin_open: true
  user: "${M_UID}:${M_GID}"
  environment:
    - USER=${USER}
    - DISPLAY=${DISPLAY}
    - ROS_MASTER_URI=http://ros1-service:11311
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all
  volumes:
    - /home/$USER:/home/$USER:rw
    - /etc/group:/etc/group:ro
    - /etc/passwd:/etc/passwd:ro
    - /etc/shadow:/etc/shadow:ro
    - /etc/sudoers.d:/etc/sudoers.d:ro
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
  # Uncomment the code below if you have an Nvidia gpu
  # (see https://docs.projectmarch.nl/doc/getting_started/setting_up_docker.html for more information)
#  deploy: # This is needed for gpu acceleration
#    resources:
#      reservations:
#        devices:
#          - capabilities: [ gpu ]

services:
  ros1-service: &ros1-service
    << : *gui-standard
    container_name: ros1
    image: ros1
    environment:
      - USER=${USER}
      - DISPLAY=${DISPLAY}
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=all
      - ROS_MASTER_URI=http://ros1-service:11311
      - ROS_DOCKER_TYPE="ros1"
      - ROS_DOCKER_START_TYPE=${ROS_DOCKER_START_TYPE}
      - ROS_ARGS
      - ROS1_ARGS
    working_dir: /home/${USER}/march/ros1
    ipc: host # The reason host is chosen (and not shareable) is so that the containers can run in isolation of eachother.
    ports: ["11311"] # Needed for rviz visualization
    command: ["bash",  "${HOME}/march/.docker_local/start_scripts/${ROS_DOCKER_START_TYPE:-bash}/ros1.bash"]

  ros2-service:
    << : *gui-standard
    container_name: ros2
    image: ros2
    environment:
      - USER=${USER}
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=http://ros1-service:11311
      - ROS_DOCKER_TYPE="ros2"
      - ROS_DOCKER_START_TYPE=${ROS_DOCKER_START_TYPE}
      - ROS_ARGS
      - ROS2_ARGS
    working_dir: /home/${USER}/march/ros2
    ipc: host # The reason host is chosen (and not container:ros1) is so that the containers can run in isolation of eachother.
    command: ["bash", "${HOME}/march/.docker_local/start_scripts/${ROS_DOCKER_START_TYPE:-bash}/ros2.bash"]

  bridge-service:
    << : *gui-standard
    container_name: bridge
    image: bridge:new2
    environment:
      - USER=${USER}
      - DISPLAY=${DISPLAY}
      - ROS_MASTER_URI=http://ros1-service:11311
      - ROS_DOCKER_TYPE="bridge"
      - ROS_DOCKER_START_TYPE=${ROS_DOCKER_START_TYPE}
    working_dir: /home/${USER}/ros1_bridge
    ipc: host # The reason host is chosen (and not container:ros1) is so that the containers can run in isolation of eachother.
    depends_on:
      - ros1-service
    command: ["bash", "${HOME}/march/.docker_local/start_scripts/${ROS_DOCKER_START_TYPE:-bash}/bridge.bash"]



