gaits:
  test_joint_gait:
    subgaits:
      perform_test: perform_test_v0
  test_joint_gait_continuous:
    subgaits:
      perform_test: perform_test_v0
positions:
  setup:
    gait_type: ''
    joints:
      linear_joint: 0.0
