gaits:
  home: {home_sit: 'home_sit_1,5sec', home_stand: 'home_stand_1,5sec'}
  single_step: {left_close: MIII, right_open: MIII}
  sit: {sit_down: MIII, sit_home: MIII}
  stand: {prepare_stand_up: MIII, stand_up: MIII}
  walk: {left_close: MIII, left_swing: MIII, right_close: MIII, right_open: MIII,
    right_swing: MIII}
