gaits:
  home: {home_sit: MIV, home_stand: MIV}
  single_step: {left_close: MIV, right_open: MIV}
  sit: {sit_down: MIV_fluent, sit_home: MIV}
  stand: {prepare_stand_up: MIV, stand_up: MIV_fluent}
  walk: {left_close: MIV, left_swing: 'MIV_1,3sec', right_close: MIV, right_open: MIV,
    right_swing: 'MIV_1,3sec'}
