gaits:
  ramp_door_last_step:
    left_close: MV_RD_laststep_leftclose_v2
    right_open: MV_RD_laststep_rightopen_v2
  ramp_door_slope_down:
    left_close: MV_RD_slopedown_leftclose_v5
    left_open: MV_RD_slopedown_leftopen_v5
    left_swing: MV_RD_slopedown_leftswing_v5
    right_close: MV_RD_slopedown_rightclose_v5
    right_open: MV_RD_slopedown_rightopen_v5
    right_swing: MV_RD_slopedown_rightswing_v5
  ramp_door_slope_down_single:
    left_close: MV_RD_slopedownsingle_leftclose_v1
    right_open: MV_RD_slopedownsingle_rightopen_v1
  ramp_door_slope_up:
    left_close: MV_RD_slopeup_leftclose_v1
    left_open: MV_RD_slopeup_leftopen_v2
    left_swing: MV_RD_slopeup_leftswing_v2
    right_close: MV_RD_slopeup_rightclose_v1
    right_open: MV_RD_slopeup_rightopen_v2
    right_swing: MV_RD_slopeup_rightswing_v2
  rough_terrain_first_middle_step:
    left_close: MV_RT_first_middlestep_leftclose_v3
    right_open: MV_RT_first_middlestep_rightopen_v2
  rough_terrain_high_step:
    left_close: MV_RT_highstep_leftclose_v8
    right_open: MV_RT_highstep_rightopen_v7
  rough_terrain_middle_steps:
    left_close: MV_RT_middlestep_leftclose_v3
    left_swing: MV_RT_middlestep_leftswing_v2
    right_open: MV_RT_middlestep_rightopen_v2
    right_swing: MV_RT_middlestep_rightswing_v2
  rough_terrain_second_middle_step:
    left_close: MV_RT_second_middlestep_leftclose_v1
    right_open: MV_RT_second_middlestep_rightopen_v1
  rough_terrain_third_middle_step:
    left_close: MV_RT_third_middlestep_leftclose_v2
    right_open: MV_RT_third_middlestep_rightopen_v2
  single_step_normal:
    left_close: MIV_final
    right_open: MIV_final
  sit:
    sit_down: MIV_final
    sit_home: MIV_final
  sofa_sit:
    sit_down: MIV_final
    sit_home: MIV_final
  sofa_stand:
    prepare_stand_up: MIV_final
    stand_up: MIV_final
  stairs_down:
    left_close: MV_stairsdown_leftclose_v5
    left_swing: MV_stairsdown_leftswing_v5
    right_close: MV_stairsdown_rightclose_v5
    right_open: MV_stairsdown_rightopen_v5
    right_swing: MV_stairsdown_rightswing_v5
  stairs_down_single_step:
    left_close: MV_stairsdown_single_leftclose_v3
    right_open: MV_stairsdown_single_rightopen_v3
  stairs_up:
    left_close: MV_stairsup_leftclose_v15
    left_swing: MV_stairsup_leftswing_v15
    right_close: MV_stairsup_rightclose_v15
    right_open: MV_stairsup_rightopen_v15a
    right_swing: MV_stairsup_rightswing_v15
  stairs_up_single_step:
    left_close: MV_stairsup_single_leftclose_v7
    right_open: MV_stairsup_single_rightopen_v7
  stand:
    prepare_stand_up: MIV_final
    stand_up: MIV_final
  tilted_path_first_end:
    left_open: MV_TPend1_leftopen_v1
    right_close: MV_TPend1_rightclose_v1
  tilted_path_first_start:
    left_open: MV_TPstart1_leftopen_v1
    right_close: MV_TPstart1_rightclose_v1
  tilted_path_left_knee_bend:
    right_open: MV_TP_left_kneebend_rightopen_v6
  tilted_path_left_single_step:
    left_close: MV_TP_left_singlestep_leftclose_v6
    right_open: MV_TP_left_singlestep_rightopen_v6
  tilted_path_left_straight_end:
    left_open: MV_TP_left_straightend_leftopen_v6
    right_close: MV_TP_left_straightend_rightclose_v6
  tilted_path_left_straight_start:
    left_close: MV_TP_left_straightstart_leftclose_v6
    right_open: MV_TP_left_straightstart_rightopen_v6
  tilted_path_right_knee_bend:
    right_open: MV_TP_right_kneebend_rightopen_v6
  tilted_path_right_single_step:
    left_open: MV_TP_right_singlestep_leftopen_v6
    right_close: MV_TP_right_singlestep_rightclose_v6
  tilted_path_right_straight_end:
    left_close: MV_TP_right_straightend_leftclose_v6
    right_open: MV_TP_right_straightend_rightopen_v6
  tilted_path_right_straight_start:
    left_open: MV_TP_right_straightstart_leftopen_v6
    right_close: MV_TP_right_straightstart_rightclose_v6
  tilted_path_second_end:
    left_open: MV_TPend2_leftopen_v1
    right_close: MV_TPend2_rightclose_v1
  tilted_path_second_start:
    left_open: MV_TPstart2_leftopen_v1
    right_close: MV_TPstart2_rightclose_v1
  walk:
    left_close: MV_walk_leftclose_v3a
    left_swing: MV_walk_leftswing_v2
    right_close: MV_walk_rightclose_v3a
    right_open: MV_walk_rightopen_v3
    right_swing: MV_walk_rightswing_v2
positions:
  stand:
    left_ankle: 0.0436
    left_hip_aa: 0.0
    left_hip_fe: -0.0873
    left_knee: 0.0
    right_ankle: 0.0436
    right_hip_aa: 0.0
    right_hip_fe: -0.0873
    right_knee: 0.0
  tilted_path_right_stand:
    left_ankle: 0.0436
    left_hip_aa: 0.0873
    left_hip_fe: -0.0873
    left_knee: 0.0
    right_ankle: 0.1309
    right_hip_aa: -0.0524
    right_hip_fe: 0.5236
    right_knee: 0.8203
  sofa_sit:
    left_ankle: 0.0436
    left_hip_aa: 0.0
    left_hip_fe: 1.5708
    left_knee: 1.7453
    right_ankle: 0.0436
    right_hip_aa: 0.0
    right_hip_fe: 1.5708
    right_knee: 1.7453
  idle_3:
    left_ankle: 0.0436
    left_hip_aa: 0.0
    left_hip_fe: -0.0873
    left_knee: 0.0
    right_ankle: 0.0436
    right_hip_aa: 0.0
    right_hip_fe: 0.1745
    right_knee: 0.4363
  slope_down_stand:
    left_ankle: -0.2618
    left_hip_aa: 0.0
    left_hip_fe: -0.0873
    left_knee: 0.0
    right_ankle: -0.2618
    right_hip_aa: 0.0
    right_hip_fe: -0.0873
    right_knee: 0.0
  sit:
    left_ankle: 0.0436
    left_hip_aa: 0.0
    left_hip_fe: 1.2217
    left_knee: 1.5708
    right_ankle: 0.0436
    right_hip_aa: 0.0
    right_hip_fe: 1.2217
    right_knee: 1.5708
  idle_6:
    left_ankle: 0.0436
    left_hip_aa: 0.0
    left_hip_fe: 0.1745
    left_knee: 0.4363
    right_ankle: 0.0436
    right_hip_aa: 0.0
    right_hip_fe: -0.0873
    right_knee: 0.0
  tilted_path_left_stand:
    left_ankle: 0.1309
    left_hip_aa: -0.0524
    left_hip_fe: 0.5236
    left_knee: 0.8203
    right_ankle: 0.0436
    right_hip_aa: 0.0873
    right_hip_fe: -0.0873
    right_knee: 0.0
