march:
  # Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

# initialize the controller
  controller:
    trajectory:
      type: model_predictive_trajectory_controller/JointTrajectoryController
      N: 10
      joints:
        - left_ankle
        - left_hip_aa
        - left_hip_fe
        - left_knee
        - right_ankle
        - right_hip_aa
        - right_hip_fe
        - right_knee

      # Controller tuning parameters
      # Q and R are the weights on the states and inputs of the system respectively
      # The parameters represent the values on the diagonal of the MPC weighting matrix
      # Both parameters are required for each joint
      weights:
        left_ankle:
          Q: [ 1000.0, 1.0 ]
          R: [ 0.001 ]

        left_hip_aa:
          Q: [ 1000.0, 1.0 ]
          R: [ 0.001 ]

        left_hip_fe:
          Q: [ 1000.0, 1.0 ]
          R: [ 0.001 ]

        left_knee:
          Q: [ 1000.0, 1.0 ]
          R: [ 0.001 ]

        right_ankle:
          Q: [ 1000.0, 1.0 ]
          R: [ 0.001 ]

        right_hip_aa:
          Q: [ 1000.0, 1.0 ]
          R: [ 0.001 ]

        right_hip_fe:
          Q: [ 1000.0, 1.0 ]
          R: [ 0.001 ]

        right_knee:
          Q: [ 1000.0, 1.0 ]
          R: [ 0.001 ]


      state_publish_rate:  25            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default

      constraints:
        goal_time: 0.1
        left_ankle:
          trajectory: 0.5
        left_hip_aa:
          trajectory: 0.5
        left_hip_fe:
          trajectory: 0.5
        left_knee:
          trajectory: 0.5
        right_ankle:
          trajectory: 0.5
        right_hip_aa:
          trajectory: 0.5
        right_hip_fe:
          trajectory: 0.5
        right_knee:
          trajectory: 0.5
