march:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    trajectory:
      full_exoskeleton:
        type: position_controllers/JointTrajectoryController
        joints:
          - test_joint