march:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    trajectory:
      testjoint:
        type: position_controllers/JointTrajectoryController
        joints:
          - test_joint
    march_state:
      type: march_state_controller/MarchStateController
      publish_rate: 50
