diag_agg:
  ros__parameters:
    pub_rate: 1.0
    inputs:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Inputs
      contains: ['input_device']
      remove_prefix: ['march_rqt_robot_monitor_node: input_device ']
    control:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Control
      contains: ['values']
      remove_prefix: ['march_rqt_robot_monitor_node: ']
    motor_controller:
      type: diagnostic_aggregator/GenericAnalyzer
      path: MotorController
      contains: ['MotorController']
      remove_prefix: ['march_rqt_robot_monitor_node: MotorController ']
    gait:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Gait
      contains: ['Gait']
      remove_prefix: ['march_rqt_robot_monitor_node: ']
    power_distribution_board:
      type: diagnostic_aggregator/GenericAnalyzer
      path: PDB
      contains: ['PowerDistributionBoard']
      remove_prefix: ['march_rqt_robot_monitor_node: PowerDistributionBoard']
    battery:
      type: diagnostic_aggregator/GenericAnalyzer
      path: Battery
      contains: ['Battery']
      remove_prefix: ['march_rqt_robot_monitor_node: Battery']
