gaits:
  ramp_up:
    left_close: MVI_rampup_leftclose_steep_v1
    left_open: MVI_rampup_leftopen_steep_v1
    left_swing: MVI_rampup_leftswing_steep_v1
    right_close: MVI_rampup_rightclose_steep_v1
    right_open: MVI_rampup_rightopen_steep_v1
    right_swing: MVI_rampup_rightswing_steep_v1

  stairs_up:
    left_close: MVI_stairsup_leftclose_cybathlon_v4
    left_swing: MVI_stairsup_leftswing_cybathlon_v4
    right_close: MVI_stairsup_rightclose_cybathlon_v4
    right_open: MVI_stairsup_rightopen_cybathlon_v4
    right_swing: MVI_stairsup_rightswing_cybathlon_v4

  stairs_down:
    left_close: MVI_stairsdown_leftclose_cybathlon_v2
    left_swing: MVI_stairsdown_leftswing_cybathlon_v2
    right_close: MVI_stairsdown_rightclose_cybathlon_v2
    right_open: MVI_stairsdown_rightopen_cybathlon_v2
    right_swing: MVI_stairsdown_rightswing_cybathlon_v2

  stairs_down_backwards:
    left_close: MVI_stairsdownbackwards_leftclose_cybathlon_v2
    left_swing: MVI_stairsdownbackwards_leftswing_cybathlon_v2
    right_close: MVI_stairsdownbackwards_rightclose_cybathlon_v2
    right_open: MVI_stairsdownbackwards_rightopen_cybathlon_v2
    right_swing: MVI_stairsdownbackwards_rightswing_cybathlon_v2

  walk:
    left_close: MVI_walk_leftclose_v3
    left_swing: MVI_walk_leftswing_v3
    right_close: MVI_walk_rightclose_v3
    right_open: MVI_walk_rightopen_v3
    right_swing: MVI_walk_rightswing_v3
  
  walk_large:
    left_close: MVI_walklarge_leftclose_v3
    left_swing: MVI_walklarge_leftswing_v3
    right_close: MVI_walklarge_rightclose_v3
    right_open: MVI_walklarge_rightopen_v3
    right_swing: MVI_walklarge_rightswing_v3
 
  walk_small:
    left_close: MVI_walksmall_leftclose_v3
    left_swing: MVI_walksmall_leftswing_v3
    right_close: MVI_walksmall_rightclose_v3
    right_open: MVI_walksmall_rightopen_v3
    right_swing: MVI_walksmall_rightswing_v3
    
  sit:
    sit_down: MVI_sit_down_v2
    sit_home: MVI_sit_home_v2
    prepare_sit_down: MVI_prepare_sit_down_v2
  
  stand:
    prepare_stand_up: MVI_prepare_stand_up_v2
    stand_up: MVI_stand_up_v2
    stand_home: MVI_stand_home_v2

positions:
  stand:
    gait_type: walk_like
    joints:
      left_ankle: 0.0
      left_hip_aa: 0.0349
      left_hip_fe: 0.0
      left_knee: 0.0
      right_ankle: 0.0
      right_hip_aa: 0.0349
      right_hip_fe: 0.0
      right_knee: 0.0
