controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - left_ankle
      - left_hip_aa
      - left_hip_fe
      - left_knee
      - right_ankle
      - right_hip_aa
      - right_hip_fe
      - right_knee
    interface_name: position
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
    gains:
      left_ankle: { p: 160.0, i: 0.0, d: 10.0, i_clamp: 100.0 }
      left_hip_aa: { p: 330.0, i: 0.0, d: 10.0, i_clamp: 100.0  }
      left_hip_fe: { p: 60.0, i: 0.0, d: 5.0, i_clamp: 100.0 }
      left_knee: { p: 60.0, i: 0.0, d: 10.0, i_clamp: 100.0 }
      right_ankle: { p: 130.0, i: 0.0, d: 10.0, i_clamp: 100.0 }
      right_hip_aa: { p: 330.0, i: 0.0, d: 10.0, i_clamp: 100.0 }
      right_hip_fe: { p: 60.0, i: 0.0, d: 5.0, i_clamp: 100.0 }
      right_knee: { p: 60.0, i: 0.0, d: 10.0, i_clamp: 100.0  }
