# this file represents the controller being used
march:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  controller:
    trajectory:
      type: model_predictive_trajectory_controller/JointTrajectoryController
      joints:
        - rotational_joint

      q_matrices:
        rotational_joint:
          n_rows: 3
          n_cols: 3
          Q: [1, 2, 3,
              4, 5, 6,
              7, 8, 9]

      state_publish_rate:  25            # Override default
      action_monitor_rate: 30            # Override default
      stop_trajectory_duration: 0        # Override default
