gaits:
  curb_sdg:
    left_close: curb_sdg_leftclose_v1
    right_open: curb_sdg_rightopen_v1
  ramp_door_last_step:
    left_close: MVI_RD_laststep_leftclose_steep_v1
    right_open: MVI_RD_laststep_rightopen_steep_v1
  ramp_door_slope_down:
    left_close: MVI_RD_slopedown_leftclose_steep_v2
    left_open: MVI_RD_slopedown_leftopen_steep_v2
    left_swing: MVI_RD_slopedown_leftswing_steep_v2
    right_close: MVI_RD_slopedown_rightclose_steep_v2
    right_open: MVI_RD_slopedown_rightopen_steep_v2
    right_swing: MVI_RD_slopedown_rightswing_steep_v2
  ramp_door_slope_down_fixed:
    left_close: MV_RD_slopedown_fixed_leftclose_v1
    left_swing: MV_RD_slopedown_fixed_leftswing_v1
    right_open: MV_RD_slopedown_fixed_rightopen_v1
    right_swing: MV_RD_slopedown_fixed_rightswing_v1
  ramp_door_slope_down_single:
    left_close: MV_RD_slopedownsingle_leftclose_v1
    right_open: MV_RD_slopedownsingle_rightopen_v1
  ramp_door_slope_up:
    left_close: MVI_RD_slopeup_leftclose_steep_v1
    left_open: MVI_RD_slopeup_leftopen_steep_v1
    left_swing: MVI_RD_slopeup_leftswing_steep_v1
    right_close: MVI_RD_slopeup_rightclose_steep_v1
    right_open: MVI_RD_slopeup_rightopen_steep_v1
    right_swing: MVI_RD_slopeup_rightswing_steep_v1
  realsense_sit:
    sit_down: MVI_sit_down_high_v1
    sit_home: MVI_sit_home_high_v1
  sit:
    sit_down: MVI_sit_down_v2
    sit_home: MVI_sit_home_v2
    prepare_sit_down: MVI_prepare_sit_down_v2
  stand:
    prepare_stand_up: MVI_prepare_stand_up_v4
    stand_up: MVI_stand_up_v4
    stand_home: MVI_stand_home_v4
  realsense_stairs_up_single_step:
    left_close: MVI_stairsup_leftclose_low_undeep
    right_open: MVI_stairsup_rightopen_low_undeep
  realsense_stand:
    prepare_stand_up: MVI_prepare_stand_up_high_v1
    stand_up: MVI_stand_up_high_v1
  rough_terrain_first_middle_step:
    left_close: MV_RT_first_middlestep_leftclose_v2
    right_open: MV_RT_first_middlestep_rightopen_v2
  rough_terrain_high_step:
    left_close: MV_RT_highstep_leftclose_v8
    right_open: MV_RT_highstep_rightopen_v6
  rough_terrain_middle_steps:
    left_close: MV_RT_middlestep_leftclose_v3
    left_swing: MV_RT_middlestep_leftswing_v2
    right_open: MV_RT_middlestep_rightopen_v2
    right_swing: MV_RT_middlestep_rightswing_v2
  rough_terrain_second_middle_step:
    left_close: MV_RT_second_middlestep_leftclose_v1
    right_open: MV_RT_second_middlestep_rightopen_v1
  rough_terrain_third_middle_step:
    left_close: MV_RT_third_middlestep_leftclose_v1
    right_open: MV_RT_third_middlestep_rightopen_v1
  side_step_right:
    right_open: MVI_sidestepright_rightopen_v1
    left_close: MVI_sidestepright_leftclose_v1
  side_step_left:
    right_close: MVI_sidestepleft_rightclose_v1
    left_open: MVI_sidestepleft_leftopen_v1
  single_step_normal:
    left_close: MIV_final
    right_open: MIV_final
  stairs_down:
    left_close: MVI_stairsdown_leftclose_cybathlon_v2
    left_swing: MVI_stairsdown_leftswing_cybathlon_v2
    right_close: MVI_stairsdown_rightclose_cybathlon_v2
    right_open: MVI_stairsdown_rightopen_cybathlon_v2
    right_swing: MVI_stairsdown_rightswing_cybathlon_v2
  stairs_down_backwards:
    left_close: MVI_stairsdownbackwards_leftclose_low_undeep_v1
    left_swing: MVI_stairsdownbackwards_leftswing_low_undeep_v1
    right_close: MVI_stairsdownbackwards_rightclose_low_undeep_v1
    right_open: MVI_stairsdownbackwards_rightopen_low_undeep_v1
    right_swing: MVI_stairsdownbackwards_rightswing_low_undeep_v1
  stairs_up:
    left_close: MVI_stairsup_leftclose_cybathlon_v4
    left_swing: MVI_stairsup_leftswing_cybathlon_v4
    right_close: MVI_stairsup_rightclose_cybathlon_v4
    right_open: MVI_stairsup_rightopen_cybathlon_v4
    right_swing: MVI_stairsup_rightswing_cybathlon_v4
  tilted_path_first_end:
    left_open: MV_TPend1_leftopen_v1
    right_close: MV_TPend1_rightclose_v1
  tilted_path_first_start:
    left_open: MV_TPstart1_leftopen_v1
    right_close: MV_TPstart1_rightclose_v1
  tilted_path_left_flexed_knee_step:
    left_close: MV_TP_left_flexed_knee_step_leftclose_v1
    right_open: MV_TP_left_flexed_knee_step_rightopen_v1
  tilted_path_left_knee_bend:
    right_open: MV_TP_left_kneebend_rightopen_v5
  tilted_path_left_single_step:
    left_close: MV_TP_left_singlestep_leftclose_v5
    right_open: MV_TP_left_singlestep_rightopen_v5
  tilted_path_left_straight_end:
    left_open: MV_TP_left_straightend_leftopen_v5
    right_close: MV_TP_left_straightend_rightclose_v5
  tilted_path_left_straight_start:
    left_close: MV_TP_left_straightstart_leftclose_v5
    right_open: MV_TP_left_straightstart_rightopen_v5
  tilted_path_right_flexed_knee_step:
    left_open: MV_TP_right_flexed_knee_step_leftopen_v1
    right_close: MV_TP_right_flexed_knee_step_rightclose_v1
  tilted_path_right_knee_bend:
    right_open: MV_TP_right_kneebend_rightopen_v5
  tilted_path_right_single_step:
    left_open: MV_TP_right_singlestep_leftopen_v5
    right_close: MV_TP_right_singlestep_rightclose_v5
  tilted_path_right_straight_end:
    left_close: MV_TP_right_straightend_leftclose_v5
    right_open: MV_TP_right_straightend_rightopen_v5
  tilted_path_right_straight_start:
    left_open: MV_TP_right_straightstart_leftopen_v5
    right_close: MV_TP_right_straightstart_rightclose_v5
  tilted_path_second_end:
    left_open: MV_TPend2_leftopen_v1
    right_close: MV_TPend2_rightclose_v1
  tilted_path_second_start:
    left_open: MV_TPstart2_leftopen_v1
    right_close: MV_TPstart2_rightclose_v1
  tilted_path_straight_start_left:
    left_open: MV_TPstraight_leftopen_v1
    right_close: MV_TPstraight_rightclose_v1
  tilted_path_straight_start_right:
    left_close: MV_TPstraight_leftclose_v1
    right_open: MV_TPstraight_rightopen_v1
  walk:
    left_close: MVI_walk_leftclose_v3
    left_swing: MVI_walk_leftswing_v3
    right_close: MVI_walk_rightclose_v3
    right_open: MVI_walk_rightopen_v3
    right_swing: MVI_walk_rightswing_v3
  walk_large:
    left_close: MVI_walklarge_leftclose_v3
    left_swing: MVI_walklarge_leftswing_v3
    right_close: MVI_walklarge_rightclose_v3
    right_open: MVI_walklarge_rightopen_v3
    right_swing: MVI_walklarge_rightswing_v3
  walk_small:
    left_close: MVI_walksmall_leftclose_v3
    left_swing: MVI_walksmall_leftswing_v3
    right_close: MVI_walksmall_rightclose_v3
    right_open: MVI_walksmall_rightopen_v3
    right_swing: MVI_walksmall_rightswing_v3
  stairs_up_single_step:
    right_open: MVI_stairsupsinglestep_rightopen_cybathlon_v4
    left_close: MVI_stairsupsinglestep_leftclose_cybathlon_v4
  stairs_down_single_step:
    left_close: MVI_stairsdownsinglestep_leftclose_cybathlon_v2
    right_open: MVI_stairsdownsinglestep_rightopen_cybathlon_v2
  stairs_down_backwards_single_step:
    left_close: MVI_stairsdownbackwardssinglestep_leftclose_cybathlon_v2
    right_open: MVI_stairsdownbackwardssinglestep_rightopen_cybathlon_v2
  walk_single_step:
    right_open: MVI_walksinglestep_rightopen_v3
    left_close: MVI_walksinglestep_leftclose_v3
  walk_single_step_large:
    right_open: MVI_walksinglesteplarge_rightopen_v3
    left_close: MVI_walksinglesteplarge_leftclose_v3
  walk_single_step_small:
    right_open: MVI_walksinglestepsmall_rightopen_v3
    left_close: MVI_walksinglestepsmall_leftclose_v3
positions:
  low_sit:
    gait_type: sit_like
    joints:
      left_ankle: 0.0
      left_hip_aa: 0.0349
      left_hip_fe: 1.5708
      left_knee: 1.8326
      right_ankle: 0.0
      right_hip_aa: 0.0349
      right_hip_fe: 1.5708
      right_knee: 1.8326
  high_sit:
    gait_type: sit_like
    joints:
      left_ankle: 0.0
      left_hip_aa: 0.0349
      left_hip_fe: 1.3963
      left_knee: 1.4835
      right_ankle: 0.0
      right_hip_aa: 0.0349
      right_hip_fe: 1.3963
      right_knee: 1.4835
  idle_1:
    gait_type: walk_like
    joints:
      left_ankle: 0.0436
      left_hip_aa: 0.0873
      left_hip_fe: -0.0873
      left_knee: 0.0
      right_ankle: 0.1309
      right_hip_aa: -0.0524
      right_hip_fe: 0.5236
      right_knee: 0.8203
  idle_10:
    gait_type: walk_like
    joints:
      left_ankle: 0.0436
      left_hip_aa: 0.0
      left_hip_fe: -0.0873
      left_knee: 0.0
      right_ankle: 0.0436
      right_hip_aa: 0.0
      right_hip_fe: 0.4014
      right_knee: 0.6981
  idle_11:
    gait_type: walk_like
    joints:
      left_ankle: 0.0436
      left_hip_aa: 0.0
      left_hip_fe: 0.4014
      left_knee: 0.6981
      right_ankle: 0.0436
      right_hip_aa: 0.0
      right_hip_fe: -0.0873
      right_knee: 0.0
  idle_2:
    gait_type: walk_like
    joints:
      left_ankle: 0.0436
      left_hip_aa: 0.0
      left_hip_fe: 1.5708
      left_knee: 1.7453
      right_ankle: 0.0436
      right_hip_aa: 0.0
      right_hip_fe: 1.5708
      right_knee: 1.7453
  idle_3:
    gait_type: walk_like
    joints:
      left_ankle: 0.0436
      left_hip_aa: 0.0
      left_hip_fe: -0.0873
      left_knee: 0.0
      right_ankle: 0.0436
      right_hip_aa: 0.0
      right_hip_fe: 0.1745
      right_knee: 0.4363
  MV_ramp_stand:
    gait_type: walk_like
    joints:
      left_ankle: -0.2618
      left_hip_aa: 0.0
      left_hip_fe: -0.0873
      left_knee: 0.0
      right_ankle: -0.2618
      right_hip_aa: 0.0
      right_hip_fe: -0.0873
      right_knee: 0.0
  flat_ramp_stand:
    gait_type: walk_like
    joints:
      left_ankle: -0.0873
      left_hip_aa: 0.0349
      left_hip_fe: -0.0873
      left_knee: 0.0
      right_ankle: -0.0873
      right_hip_aa: 0.0349
      right_hip_fe: -0.0873
      right_knee: 0.0
  steep_ramp_stand:
    gait_type: walk_like
    joints:
      left_ankle: -0.2618
      left_hip_aa: 0.0349
      left_hip_fe: -0.0873
      left_knee: 0.0
      right_ankle: -0.2618
      right_hip_aa: 0.0349
      right_hip_fe: -0.0873
      right_knee: 0.0
  idle_6:
    gait_type: walk_like
    joints:
      left_ankle: 0.0436
      left_hip_aa: 0.0
      left_hip_fe: 0.1745
      left_knee: 0.4363
      right_ankle: 0.0436
      right_hip_aa: 0.0
      right_hip_fe: -0.0873
      right_knee: 0.0
  idle_7:
    gait_type: walk_like
    joints:
      left_ankle: 0.1309
      left_hip_aa: -0.0524
      left_hip_fe: 0.5236
      left_knee: 0.8203
      right_ankle: 0.0436
      right_hip_aa: 0.0873
      right_hip_fe: -0.0873
      right_knee: 0.0
  idle_8:
    gait_type: walk_like
    joints:
      left_ankle: 0.0436
      left_hip_aa: 0.1222
      left_hip_fe: -0.0873
      left_knee: 0.0
      right_ankle: 0.0436
      right_hip_aa: -0.0873
      right_hip_fe: 0.6109
      right_knee: 0.9076
  idle_9:
    gait_type: walk_like
    joints:
      left_ankle: 0.0436
      left_hip_aa: -0.0873
      left_hip_fe: 0.6109
      left_knee: 0.9076
      right_ankle: 0.0436
      right_hip_aa: 0.1222
      right_hip_fe: -0.0873
      right_knee: 0.0
  sit_without_haa:
    gait_type: sit_like
    joints:
      left_ankle: 0.0
      left_hip_aa: 0.0349
      left_hip_fe: 1.4835
      left_knee: 1.4835
      right_ankle: 0.0
      right_hip_aa: 0.0349
      right_hip_fe: 1.4835
      right_knee: 1.4835
  sit_with_haa:
    gait_type: sit_like
    joints:
      left_ankle: 0.0
      left_hip_aa: 0.0
      left_hip_fe: 1.4835
      left_knee: 1.4835
      right_ankle: 0.0
      right_hip_aa: 0.0
      right_hip_fe: 1.4835
      right_knee: 1.4835
  stand:
    gait_type: walk_like
    joints:
      left_ankle: 0.0
      left_hip_aa: 0.0349
      left_hip_fe: 0.0
      left_knee: 0.0
      right_ankle: 0.0
      right_hip_aa: 0.0349
      right_hip_fe: 0.0
      right_knee: 0.0
dynamic_edge_gaits:
  dynamic_sit:
    sit_down: MIV_final
    sit_home: MIV_final
  dynamic_stand:
    prepare_stand_up: MIV_final
    stand_up: MIV_final
