march:
  controller:
    state:
      type: joint_state_controller/JointStateController
      publish_rate: 50
    position:
      left_hip_joint:
        type: position_controllers/JointPositionController
        joint: left_hip
    trajectory:
      full_exoskeleton:
        type: position_controllers/JointTrajectoryController
        joints:
          - right_hip
          - left_hip
          - right_knee
          - left_knee
          - right_ankle
          - left_ankle