gaits:
  curb_sdg:
    left_close: curb_sdg_leftclose_v1
    right_open: curb_sdg_rightopen_v1
  ramp_door_last_step:
    left_close: MVI_RD_laststep_leftclose_steep_v1
    right_open: MVI_RD_laststep_rightopen_steep_v1
  ramp_door_slope_down:
    left_close: MVI_RD_slopedown_leftclose_steep_v2
    left_open: MVI_RD_slopedown_leftopen_steep_v2
    left_swing: MVI_RD_slopedown_leftswing_steep_v2
    right_close: MVI_RD_slopedown_rightclose_steep_v2
    right_open: MVI_RD_slopedown_rightopen_steep_v2
    right_swing: MVI_RD_slopedown_rightswing_steep_v2
  ramp_door_slope_up:
    left_close: MVI_RD_slopeup_leftclose_steep_v1
    left_open: MVI_RD_slopeup_leftopen_steep_v1
    left_swing: MVI_RD_slopeup_leftswing_steep_v1
    right_close: MVI_RD_slopeup_rightclose_steep_v1
    right_open: MVI_RD_slopeup_rightopen_steep_v1
    right_swing: MVI_RD_slopeup_rightswing_steep_v1
  realsense_sit:
    sit_down: MVI_sit_down_high_v1
    sit_home: MVI_sit_home_high_v1
  realsense_stand:
    prepare_stand_up: MVI_prepare_stand_up_high_v1
    stand_up: MVI_stand_up_high_v1
  side_step_right:
    right_open: MVI_sidestepright_rightopen_v1
    left_close: MVI_sidestepright_leftclose_v1
  side_step_left:
    right_close: MVI_sidestepleft_rightclose_v1
    left_open: MVI_sidestepleft_leftopen_v1
  sit:
    sit_down: MVI_sit_down_v2
    sit_home: MVI_sit_home_v2
    prepare_sit_down: MVI_prepare_sit_down_v2
  stairs_down:
    left_close: MVI_stairsdown_leftclose_cybathlon_v2
    left_swing: MVI_stairsdown_leftswing_cybathlon_v2
    right_close: MVI_stairsdown_rightclose_cybathlon_v2
    right_open: MVI_stairsdown_rightopen_cybathlon_v2
    right_swing: MVI_stairsdown_rightswing_cybathlon_v2
  stairs_down_backwards:
    left_close: MVI_stairsdownbackwards_leftclose_low_undeep_v1
    left_swing: MVI_stairsdownbackwards_leftswing_low_undeep_v1
    right_close: MVI_stairsdownbackwards_rightclose_low_undeep_v1
    right_open: MVI_stairsdownbackwards_rightopen_low_undeep_v1
    right_swing: MVI_stairsdownbackwards_rightswing_low_undeep_v1
  stairs_down_single_step:
    left_close: MVI_stairsdownsinglestep_leftclose_cybathlon_v3
    right_open: MVI_stairsdownsinglestep_rightopen_cybathlon_v3
  stairs_down_backwards_single_step:
    left_close: MVI_stairsdownbackwardssinglestep_leftclose_cybathlon_v5
    right_open: MVI_stairsdownbackwardssinglestep_rightopen_cybathlon_v5
  stairs_up:
    left_close: MVI_stairsup_leftclose_cybathlon_v4
    left_swing: MVI_stairsup_leftswing_cybathlon_v4
    right_close: MVI_stairsup_rightclose_cybathlon_v4
    right_open: MVI_stairsup_rightopen_cybathlon_v4
    right_swing: MVI_stairsup_rightswing_cybathlon_v4
  stairs_up_single_step:
    right_open: MVI_stairsupsinglestep_rightopen_cybathlon_v5
    left_close: MVI_stairsupsinglestep_leftclose_cybathlon_v5
  stand:
    prepare_stand_up: MVI_prepare_stand_up_v2
    stand_up: MVI_stand_up_v2
    stand_home: MVI_stand_home_v2
  walk:
    left_close: MVI_walk_leftclose_v7
    left_swing: MVI_walk_leftswing_v7
    right_close: MVI_walk_rightclose_v7
    right_open: MVI_walk_rightopen_v7
    right_swing: MVI_walk_rightswing_v7
  walk_large:
    left_close: MVI_walklarge_leftclose_v3
    left_swing: MVI_walklarge_leftswing_v3
    right_close: MVI_walklarge_rightclose_v3
    right_open: MVI_walklarge_rightopen_v3
    right_swing: MVI_walklarge_rightswing_v3
  walk_small:
    left_close: MVI_walksmall_leftclose_v3
    left_swing: MVI_walksmall_leftswing_v3
    right_close: MVI_walksmall_rightclose_v3
    right_open: MVI_walksmall_rightopen_v3
    right_swing: MVI_walksmall_rightswing_v3
positions:
  ten_degree_hip_stand:
    gait_type: walk_like
    joints:
      left_ankle: 0.0
      left_hip_aa: 0.0349
      left_hip_fe: -0.1745
      left_knee: 0.0
      right_ankle: 0.0
      right_hip_aa: 0.0349
      right_hip_fe: -0.1745
      right_knee: 0.0
  low_sit:
    gait_type: sit_like
    joints:
      left_ankle: 0.0
      left_hip_aa: 0.0349
      left_hip_fe: 1.5708
      left_knee: 1.8326
      right_ankle: 0.0
      right_hip_aa: 0.0349
      right_hip_fe: 1.5708
      right_knee: 1.8326
  high_sit:
    gait_type: sit_like
    joints:
      left_ankle: 0.0
      left_hip_aa: 0.0349
      left_hip_fe: 1.3963
      left_knee: 1.4835
      right_ankle: 0.0
      right_hip_aa: 0.0349
      right_hip_fe: 1.3963
      right_knee: 1.4835
  flat_ramp_stand:
    gait_type: walk_like
    joints:
      left_ankle: -0.0873
      left_hip_aa: 0.0349
      left_hip_fe: -0.0873
      left_knee: 0.0
      right_ankle: -0.0873
      right_hip_aa: 0.0349
      right_hip_fe: -0.0873
      right_knee: 0.0
  steep_ramp_stand:
    gait_type: walk_like
    joints:
      left_ankle: -0.2618
      left_hip_aa: 0.0349
      left_hip_fe: -0.0873
      left_knee: 0.0
      right_ankle: -0.2618
      right_hip_aa: 0.0349
      right_hip_fe: -0.0873
      right_knee: 0.0
  sit_without_haa:
    gait_type: sit_like
    joints:
      left_ankle: 0.0
      left_hip_aa: 0.0349
      left_hip_fe: 1.4835
      left_knee: 1.4835
      right_ankle: 0.0
      right_hip_aa: 0.0349
      right_hip_fe: 1.4835
      right_knee: 1.4835
  sit_with_haa:
    gait_type: sit_like
    joints:
      left_ankle: 0.0
      left_hip_aa: 0.0
      left_hip_fe: 1.4835
      left_knee: 1.4835
      right_ankle: 0.0
      right_hip_aa: 0.0
      right_hip_fe: 1.4835
      right_knee: 1.4835
  stand:
    gait_type: walk_like
    joints:
      left_ankle: 0.0
      left_hip_aa: 0.0349
      left_hip_fe: -0.1745
      left_knee: 0.0
      right_ankle: 0.0
      right_hip_aa: 0.0349
      right_hip_fe: -0.1745
      right_knee: 0.0
dynamic_edge_gaits:
  dynamic_sit:
    sit_down: MIV_final
    sit_home: MIV_final
  dynamic_stand:
    prepare_stand_up: MIV_final
    stand_up: MIV_final
