march:
  controller:
    joint_state:
      type: joint_state_controller/JointStateController
      publish_rate: 250

    # Regular PID trajectory effort controller
    trajectory:
      type: effort_controllers/JointTrajectoryController
      joints:
        - left_ankle
        - left_hip_fe
        - left_knee
        - right_ankle
        - right_hip_fe
        - right_knee

      gains:
        left_ankle: {p: 160, i: 0, d: 10, i_clamp: 100, publish_state: true, antiwindup: true}
        left_hip_fe: {p: 60, i: 0, d: 5, i_clamp: 100, publish_state: true, antiwindup: true}
        left_knee: {p: 60, i: 0, d: 10, i_clamp: 100, publish_state: true, antiwindup: true}
        right_ankle: {p: 130, i: 0, d: 10, i_clamp: 100, publish_state: true, antiwindup: true}
        right_hip_fe: {p: 60, i: 0, d: 5, i_clamp: 100, publish_state: true, antiwindup: true}
        right_knee: {p: 60, i: 0, d: 10, i_clamp: 100, publish_state: true, antiwindup: true}

      constraints:
        goal_time: 0.5
        left_ankle:
          margin_soft_limit_error: 0.5
          trajectory: 2.0
          goal: 2.0
        left_hip_fe:
          margin_soft_limit_error: 0.5
          trajectory: 2.0
          goal: 2.0
        left_knee:
          margin_soft_limit_error: 0.5
          trajectory: 2.0
          goal: 2.0
        right_ankle:
          margin_soft_limit_error: 0.5
          trajectory: 2.0
          goal: 2.0
        right_hip_fe:
          margin_soft_limit_error: 0.5
          trajectory: 2.0
          goal: 2.0
        right_knee:
          margin_soft_limit_error: 0.5
          trajectory: 2.0
          goal: 2.0
        left_hip_aa:
          margin_soft_limit_error: 0.5
        right_hip_aa:
          margin_soft_limit_error: 0.5

    # Trajectory effort controller specifically for MPC
    # TODO: actually use MPC here
    trajectory_mpc:
      type: model_predictive_trajectory_controller/JointTrajectoryController
      N: 20
      joints:
        - left_hip_aa
        - right_hip_aa

      weights:
        left_hip_aa:
          Q: [ 100.0, 1.0 ]
          R: [ 0.01 ]

        right_hip_aa:
#          Q: [ 100.0, 1.0 ]
          R: [ 0.01 ]

      constraints:
        goal_time: 0.5
        left_hip_aa:
          margin_soft_limit_error: 0.5
          trajectory: 2.0
          goal: 2.0
        right_hip_aa:
          margin_soft_limit_error: 0.5
          trajectory: 2.0
          goal: 2.0
