march:
  controller:
    pdb_state:
      type: march_pdb_state_controller/MarchPdbStateController
      publish_rate: 50
    joint_state:
      type: joint_state_controller/JointStateController
      publish_rate: 250
    temperature_sensor:
      type: march_temperature_sensor_controller/MarchTemperatureSensorController
      publish_rate: 1
    trajectory:
      type: effort_controllers/JointTrajectoryController
      joints:
        - rotational_joint
      gains:
        rotational_joint: {p: 1, i: 0, d: 0, i_clamp: 100, publish_state: true, antiwindup: true}
      constraints:
        rotational_joint:
          margin_soft_limit_error: 0.5
          goal: 0.5
          trajectory: 0.5