gait_types:
  sit_like:
    left_ankle: {p: 50, i: 0, d: 3}
    left_hip_aa: {p: 150, i: 0, d: 10}
    left_hip_fe: {p: 60, i: 0, d: 5}
    left_knee: {p: 60, i: 0, d: 5}
    right_ankle: {p: 50, i: 0, d: 3}
    right_hip_aa: {p: 150, i: 0, d: 10}
    right_hip_fe: {p: 60, i: 0, d: 5}
    right_knee: {p: 60, i: 0, d: 5}
  walk_like:
    left_ankle: {p: 50, i: 0, d: 3}
    left_hip_aa: {p: 150, i: 0, d: 10}
    left_hip_fe: {p: 60, i: 0, d: 5}
    left_knee: {p: 60, i: 0, d: 5}
    right_ankle: {p: 50, i: 0, d: 3}
    right_hip_aa: {p: 150, i: 0, d: 10}
    right_hip_fe: {p: 60, i: 0, d: 5}
    right_knee: {p: 60, i: 0, d: 5}
  stairs_like:
    left_ankle: {p: 50, i: 0, d: 3}
    left_hip_aa: {p: 150, i: 0, d: 10}
    left_hip_fe: {p: 60, i: 0, d: 5}
    left_knee: {p: 60, i: 0, d: 5}
    right_ankle: {p: 50, i: 0, d: 3}
    right_hip_aa: {p: 150, i: 0, d: 10}
    right_hip_fe: {p: 60, i: 0, d: 5}
    right_knee: {p: 60, i: 0, d: 5}