controller_list:
  - name: fake_chain_rl_controller
    type: $(arg execution_type)
    joints:
      - right_ankle
      - right_knee
      - right_hip_fe
      - right_hip_aa
      - left_hip_aa
      - left_hip_fe
      - left_knee
      - left_ankle
  - name: fake_end_effector_controller
    type: $(arg execution_type)
    joints:
      - left_ankle
initial:  # Define initial robot poses.
#  - group: chain_rl
#    pose: home

  []