joint_layout:
  left_hip: {row: 0, column: 0}
  right_hip: {row: 0, column: 1}
  left_knee: {row: 1, column: 0}
  right_knee: {row: 1, column: 1}
  left_ankle: {row: 2, column: 0}
  right_ankle: {row: 2, column: 1}
