march:
  controller:
    pdb_state:
      type: march_pdb_state_controller/MarchPdbStateController
      publish_rate: 50
    joint_state:
      type: joint_state_controller/JointStateController
      publish_rate: 250
    temperature_sensor:
      type: march_temperature_sensor_controller/MarchTemperatureSensorController
      publish_rate: 1
    trajectory:
      type: effort_controllers/JointTrajectoryController
      allow_partial_joints_goal: true
      joints:
        - left_hip_aa
        - left_hip_fe
      gains: # Required because we're controlling an effort interface
        left_hip_aa: {p: 150, i: 0, d: 10, i_clamp: 100, publish_state: true, antiwindup: true}
        left_hip_fe: {p: 60, i: 0, d: 5, i_clamp: 100, publish_state: true, antiwindup: true}

      constraints:
        goal_time: 0.2
        left_hip_aa:
          margin_soft_limit_error: 0.5
          trajectory: 0.305
          goal: 0.305
        left_hip_fe:
          margin_soft_limit_error: 0.5
          trajectory: 0.305
          goal: 0.305